DISPLAY "---------------------------------------"
DISPLAY "SIMPLE ARITHMETICS, DECLARATION, OUTPUT"
SET X TO 5
SET Y TO 10
5 MULTIPLIED BY 10 DIVIDED BY 2 PLUS 5 MINUS 10 GIVING Z
10 MINUS 5 DIVIDED BY 5 MULTIPLIED BY 2 GIVING A
DISPLAY X, Y, Z, A

ADD X TO Y
DISPLAY Y

SUBTRACT Y FROM X
DISPLAY X

DISPLAY "---------------------------------------"


SET NAME TO "PETER"
SET PRICE TO [5, 3, 2, 10]
SET ITEM TO ["BREAD", "ONION", "APPLE", "ICE CREAM"]

DISPLAY NAME PLUS "'S", "SHOPPING LIST"
DISPLAY "----------------"
SET COUNTER TO 1
SET TOTAL TO 0
WHILE COUNTER LESS THAN 5
    DISPLAY "|", ITEM AT COUNTER, PRICE AT COUNTER
    ADD PRICE AT COUNTER TO TOTAL
    ADD 1 TO COUNTER
END WHILE
DISPLAY "----------------"

DISPLAY NAME, "OWES", TOTAL, "SEK"


DISPLAY "---------------------------------------"
DISPLAY "RECURSIVE FACTORIAL FUNCTION 10!"

DEFINE FUNCTION FACTORIAL WITH N
    IF N LESS THAN 2
        RETURN 1
    END IF
    RETURN N MULTIPLIED BY FACTORIAL WITH N MINUS 1
END FUNCTION

DISPLAY FACTORIAL WITH 10
DISPLAY "---------------------------------------"

DISPLAY "COMPARE FUNCTION:"
DISPLAY ""

DEFINE FUNCTION COMPARE_NUMBERS WITH NUMBER_A, NUMBER_B

    IF NUMBER_A GREATER THAN NUMBER_B
        DISPLAY NUMBER_A, "IS GREATER THAN", NUMBER_B
    ELSE IF NUMBER_B GREATER THAN NUMBER_A
        DISPLAY NUMBER_B, "IS GREATER THAN", NUMBER_A
    ELSE
        DISPLAY NUMBER_A, "AND", NUMBER_B, "ARE THE SAME"
    END IF

END FUNCTION


COMPARE_NUMBERS WITH 5, 10
COMPARE_NUMBERS WITH 2, 1
COMPARE_NUMBERS WITH 7, 7
COMPARE_NUMBERS WITH X, Y


DISPLAY "---------------------------------------"

DISPLAY "IF 5 GREATER THAN 4 AND 6 NOT EQUAL 3"
IF 5 GREATER THAN 4 AND 6 NOT EQUAL 3
    DISPLAY "TRUE"
END IF

DISPLAY "IF 5 AND 3 GREATER THAN 4"
IF 5 AND 3 GREATER THAN 4
    DISPLAY "TRUE"
ELSE 
    DISPLAY "FALSE"
END IF

DISPLAY "---------------------------------------"

DEFINE FUNCTION HELLO
    RETURN "GREETINGS"
END FUNCTION

DISPLAY HELLO

SET GREET TO HELLO
DISPLAY GREET

ADD GREET PLUS HELLO TO GREET
DISPLAY GREET

DISPLAY "---------------------------------------"
